//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoViewApp.WP81.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoViewApp.WP81.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BING.
        /// </summary>
        public static string Bing {
            get {
                return ResourceManager.GetString("Bing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh your day with a new cover photo from Bing everyday. If you choose this option, you agree that all rights belong to the respective owners of the image..
        /// </summary>
        public static string BingText {
            get {
                return ResourceManager.GetString("BingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bye bye.
        /// </summary>
        public static string ByeBye {
            get {
                return ResourceManager.GetString("ByeBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERIC NEWS TOPIC.
        /// </summary>
        public static string GenericNewsTopic {
            get {
                return ResourceManager.GetString("GenericNewsTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love News, Sports or Finance? We got you covered. Choose this option if you would like to see a broader news topic..
        /// </summary>
        public static string GenericNewsTopicText {
            get {
                return ResourceManager.GetString("GenericNewsTopicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe around to pick a best view. When done, click &apos;That&apos;s it!&apos;.
        /// </summary>
        public static string ImageCropping {
            get {
                return ResourceManager.GetString("ImageCropping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer your own image as your lock screen? or, we will get a perfect one for you from Bing..
        /// </summary>
        public static string ImageSourceSelection {
            get {
                return ResourceManager.GetString("ImageSourceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to read in your lock screen? Select a category from below..
        /// </summary>
        public static string Interest {
            get {
                return ResourceManager.GetString("Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump in!.
        /// </summary>
        public static string JumpIn {
            get {
                return ResourceManager.GetString("JumpIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE LEARNING.
        /// </summary>
        public static string LanguageLearning {
            get {
                return ResourceManager.GetString("LanguageLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform your phone into a best language learning tool. Learn a new word from a language of your choice right from the lock screen!.
        /// </summary>
        public static string LanguageLearningText {
            get {
                return ResourceManager.GetString("LanguageLearningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to learn today?.
        /// </summary>
        public static string LanguageSetting {
            get {
                return ResourceManager.GetString("LanguageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s go!.
        /// </summary>
        public static string LetsGo {
            get {
                return ResourceManager.GetString("LetsGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock screen.
        /// </summary>
        public static string lockscreen {
            get {
                return ResourceManager.GetString("lockscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mundane.
        /// </summary>
        public static string mundane {
            get {
                return ResourceManager.GetString("mundane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIFIC TOPIC OF YOUR CHOICE.
        /// </summary>
        public static string SpecificTopicOfYourChoice {
            get {
                return ResourceManager.GetString("SpecificTopicOfYourChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows user to use a specific topic of their interest. For example, if you are interested in Microsoft news, just type in Microsoft and we&apos;ll gather you the hottest and latest Microsoft news..
        /// </summary>
        public static string SpecificTopicOfYourChoiceText {
            get {
                return ResourceManager.GetString("SpecificTopicOfYourChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        public static string Sports {
            get {
                return ResourceManager.GetString("Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stories.
        /// </summary>
        public static string Stories {
            get {
                return ResourceManager.GetString("Stories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Source.
        /// </summary>
        public static string SuggestedSource {
            get {
                return ResourceManager.GetString("SuggestedSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s it!.
        /// </summary>
        public static string ThatsIt {
            get {
                return ResourceManager.GetString("ThatsIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Language.
        /// </summary>
        public static string TranslationLanguage {
            get {
                return ResourceManager.GetString("TranslationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE MY OWN IMAGE.
        /// </summary>
        public static string UseOwnImage {
            get {
                return ResourceManager.GetString("UseOwnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this if you would like to use the same image as your lock screen over time. In the next step we will let you pick one from your library..
        /// </summary>
        public static string UseOwnImageText {
            get {
                return ResourceManager.GetString("UseOwnImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORD OF WISDOM.
        /// </summary>
        public static string WordOfWisdom {
            get {
                return ResourceManager.GetString("WordOfWisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank, or use a sentence that you&apos;ve been telling yourself..
        /// </summary>
        public static string WordOfWisdomText {
            get {
                return ResourceManager.GetString("WordOfWisdomText", resourceCulture);
            }
        }
    }
}
