//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoViewApp.WP81.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoViewApp.WP81.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alice Blue.
        /// </summary>
        public static string AliceBlue {
            get {
                return ResourceManager.GetString("AliceBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize.
        /// </summary>
        public static string AllDone {
            get {
                return ResourceManager.GetString("AllDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;re the final tweaks....
        /// </summary>
        public static string AllSetPageIntro {
            get {
                return ResourceManager.GetString("AllSetPageIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks! You&apos;re all set..
        /// </summary>
        public static string AllSetTitleText {
            get {
                return ResourceManager.GetString("AllSetTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antique White.
        /// </summary>
        public static string AntiqueWhite {
            get {
                return ResourceManager.GetString("AntiqueWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqua.
        /// </summary>
        public static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquamarine.
        /// </summary>
        public static string Aquamarine {
            get {
                return ResourceManager.GetString("Aquamarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average updates/day:.
        /// </summary>
        public static string AverageRequestPerDay {
            get {
                return ResourceManager.GetString("AverageRequestPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is on average the number of updates you will receive per day..
        /// </summary>
        public static string AverageRequestPerDayExplained {
            get {
                return ResourceManager.GetString("AverageRequestPerDayExplained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure.
        /// </summary>
        public static string Azure {
            get {
                return ResourceManager.GetString("Azure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens if my balance runs out?.
        /// </summary>
        public static string BalanceRunOut {
            get {
                return ResourceManager.GetString("BalanceRunOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your balance runs out, you will still receive updates, but at a significantly lowered rate. We&apos;ll remind you if you&apos;re out of balance soon..
        /// </summary>
        public static string BalanceRunOutPromptText {
            get {
                return ResourceManager.GetString("BalanceRunOutPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT IF QUOTA RUNS OUT....
        /// </summary>
        public static string BalanceRunOutPromptTitle {
            get {
                return ResourceManager.GetString("BalanceRunOutPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beige.
        /// </summary>
        public static string Beige {
            get {
                return ResourceManager.GetString("Beige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BING.
        /// </summary>
        public static string Bing {
            get {
                return ResourceManager.GetString("Bing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh your day with a new cover photo from Bing everyday. If you choose this option, you agree that all rights belong to the respective owners of the image..
        /// </summary>
        public static string BingText {
            get {
                return ResourceManager.GetString("BingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisque.
        /// </summary>
        public static string Bisque {
            get {
                return ResourceManager.GetString("Bisque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blanched Almond.
        /// </summary>
        public static string BlanchedAlmond {
            get {
                return ResourceManager.GetString("BlanchedAlmond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Violet.
        /// </summary>
        public static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a news source, then select a category to continue..
        /// </summary>
        public static string BroadInterestTopicPageIntro {
            get {
                return ResourceManager.GetString("BroadInterestTopicPageIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burly Wood.
        /// </summary>
        public static string BurlyWood {
            get {
                return ResourceManager.GetString("BurlyWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bye bye.
        /// </summary>
        public static string ByeBye {
            get {
                return ResourceManager.GetString("ByeBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadet Blue.
        /// </summary>
        public static string CadetBlue {
            get {
                return ResourceManager.GetString("CadetBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETERMINING YOUR PRICE.
        /// </summary>
        public static string CalcPriceCaption {
            get {
                return ResourceManager.GetString("CalcPriceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated days per $0.99 lasts:.
        /// </summary>
        public static string CalculatedDaysPer099Lasts {
            get {
                return ResourceManager.GetString("CalculatedDaysPer099Lasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chartreuse.
        /// </summary>
        public static string Chartreuse {
            get {
                return ResourceManager.GetString("Chartreuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolate.
        /// </summary>
        public static string Chocolate {
            get {
                return ResourceManager.GetString("Chocolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute Price:.
        /// </summary>
        public static string ComputePrice {
            get {
                return ResourceManager.GetString("ComputePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is what our service provider charges us for computing. If our service provider lowers their traffic price, we&apos;ll lower ours too!.
        /// </summary>
        public static string ComputePriceExplained {
            get {
                return ResourceManager.GetString("ComputePriceExplained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Background.
        /// </summary>
        public static string ContentBackground {
            get {
                return ResourceManager.GetString("ContentBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Font Size.
        /// </summary>
        public static string ContentFontSize {
            get {
                return ResourceManager.GetString("ContentFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Foreground.
        /// </summary>
        public static string ContentForeground {
            get {
                return ResourceManager.GetString("ContentForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking.
        /// </summary>
        public static string Cooking {
            get {
                return ResourceManager.GetString("Cooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coral.
        /// </summary>
        public static string Coral {
            get {
                return ResourceManager.GetString("Coral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cornflower Blue.
        /// </summary>
        public static string CornflowerBlue {
            get {
                return ResourceManager.GetString("CornflowerBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cornsilk.
        /// </summary>
        public static string Cornsilk {
            get {
                return ResourceManager.GetString("Cornsilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crimson.
        /// </summary>
        public static string Crimson {
            get {
                return ResourceManager.GetString("Crimson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customized.
        /// </summary>
        public static string Customized {
            get {
                return ResourceManager.GetString("Customized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        public static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Blue.
        /// </summary>
        public static string DarkBlue {
            get {
                return ResourceManager.GetString("DarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Cyan.
        /// </summary>
        public static string DarkCyan {
            get {
                return ResourceManager.GetString("DarkCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Goldenrod.
        /// </summary>
        public static string DarkGoldenrod {
            get {
                return ResourceManager.GetString("DarkGoldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Gray.
        /// </summary>
        public static string DarkGray {
            get {
                return ResourceManager.GetString("DarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Green.
        /// </summary>
        public static string DarkGreen {
            get {
                return ResourceManager.GetString("DarkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Khaki.
        /// </summary>
        public static string DarkKhaki {
            get {
                return ResourceManager.GetString("DarkKhaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Magenta.
        /// </summary>
        public static string DarkMagenta {
            get {
                return ResourceManager.GetString("DarkMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Olive Green.
        /// </summary>
        public static string DarkOliveGreen {
            get {
                return ResourceManager.GetString("DarkOliveGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Orange.
        /// </summary>
        public static string DarkOrange {
            get {
                return ResourceManager.GetString("DarkOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Orchid.
        /// </summary>
        public static string DarkOrchid {
            get {
                return ResourceManager.GetString("DarkOrchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Red.
        /// </summary>
        public static string DarkRed {
            get {
                return ResourceManager.GetString("DarkRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Salmon.
        /// </summary>
        public static string DarkSalmon {
            get {
                return ResourceManager.GetString("DarkSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Sea Green.
        /// </summary>
        public static string DarkSeaGreen {
            get {
                return ResourceManager.GetString("DarkSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Slate Blue.
        /// </summary>
        public static string DarkSlateBlue {
            get {
                return ResourceManager.GetString("DarkSlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Slate Gray.
        /// </summary>
        public static string DarkSlateGray {
            get {
                return ResourceManager.GetString("DarkSlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Turquoise.
        /// </summary>
        public static string DarkTurquoise {
            get {
                return ResourceManager.GetString("DarkTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Violet.
        /// </summary>
        public static string DarkViolet {
            get {
                return ResourceManager.GetString("DarkViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days for $0.99.
        /// </summary>
        public static string DaysFor099 {
            get {
                return ResourceManager.GetString("DaysFor099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Pink.
        /// </summary>
        public static string DeepPink {
            get {
                return ResourceManager.GetString("DeepPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Sky Blue.
        /// </summary>
        public static string DeepSkyBlue {
            get {
                return ResourceManager.GetString("DeepSkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim Gray.
        /// </summary>
        public static string DimGray {
            get {
                return ResourceManager.GetString("DimGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodger Blue.
        /// </summary>
        public static string DodgerBlue {
            get {
                return ResourceManager.GetString("DodgerBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic.
        /// </summary>
        public static string Domestic {
            get {
                return ResourceManager.GetString("Domestic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not disturb.
        /// </summary>
        public static string DoNotDisturbTitle {
            get {
                return ResourceManager.GetString("DoNotDisturbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What if I don&apos;t want to pay?.
        /// </summary>
        public static string DontWantToPay {
            get {
                return ResourceManager.GetString("DontWantToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Do not disturb during night..
        /// </summary>
        public static string EnableDoNotDisturbDuring {
            get {
                return ResourceManager.GetString("EnableDoNotDisturbDuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        public static string Entertainment {
            get {
                return ResourceManager.GetString("Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnUs {
            get {
                return ResourceManager.GetString("EnUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Estimated).
        /// </summary>
        public static string Estimated {
            get {
                return ResourceManager.GetString("Estimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firebrick.
        /// </summary>
        public static string Firebrick {
            get {
                return ResourceManager.GetString("Firebrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floral White.
        /// </summary>
        public static string FloralWhite {
            get {
                return ResourceManager.GetString("FloralWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize the portion of the text you chose with new color and size..
        /// </summary>
        public static string FontCASPageIntro {
            get {
                return ResourceManager.GetString("FontCASPageIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest Green.
        /// </summary>
        public static string ForestGreen {
            get {
                return ResourceManager.GetString("ForestGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuchsia.
        /// </summary>
        public static string Fuchsia {
            get {
                return ResourceManager.GetString("Fuchsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gainsboro.
        /// </summary>
        public static string Gainsboro {
            get {
                return ResourceManager.GetString("Gainsboro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERIC NEWS TOPIC.
        /// </summary>
        public static string GenericNewsTopic {
            get {
                return ResourceManager.GetString("GenericNewsTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love News, Sports or Finance? We got you covered. Choose this option if you would like to see a broader news topic..
        /// </summary>
        public static string GenericNewsTopicText {
            get {
                return ResourceManager.GetString("GenericNewsTopicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghost White.
        /// </summary>
        public static string GhostWhite {
            get {
                return ResourceManager.GetString("GhostWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goldenrod.
        /// </summary>
        public static string Goldenrod {
            get {
                return ResourceManager.GetString("Goldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great!.
        /// </summary>
        public static string Great {
            get {
                return ResourceManager.GetString("Great", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Yellow.
        /// </summary>
        public static string GreenYellow {
            get {
                return ResourceManager.GetString("GreenYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honeydew.
        /// </summary>
        public static string Honeydew {
            get {
                return ResourceManager.GetString("Honeydew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotPicks.
        /// </summary>
        public static string Hotpicks {
            get {
                return ResourceManager.GetString("Hotpicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Pink.
        /// </summary>
        public static string HotPink {
            get {
                return ResourceManager.GetString("HotPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe around to pick a best view. When done, click &apos;That&apos;s it!&apos;.
        /// </summary>
        public static string ImageCropping {
            get {
                return ResourceManager.GetString("ImageCropping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer your own image as your lock screen? or, we will get a perfect one for you from Bing..
        /// </summary>
        public static string ImageSourceSelection {
            get {
                return ResourceManager.GetString("ImageSourceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian Red.
        /// </summary>
        public static string IndianRed {
            get {
                return ResourceManager.GetString("IndianRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        public static string Indigo {
            get {
                return ResourceManager.GetString("Indigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to read in your lock screen? You can select some from below..
        /// </summary>
        public static string Interest {
            get {
                return ResourceManager.GetString("Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select multiple categories. If we cannot fit all the contents on your screen, some of them will be dropped until next time they fit..
        /// </summary>
        public static string InterestSelectionGuide {
            get {
                return ResourceManager.GetString("InterestSelectionGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup  Interest... Step .
        /// </summary>
        public static string InterestSelectionProgress {
            get {
                return ResourceManager.GetString("InterestSelectionProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivory.
        /// </summary>
        public static string Ivory {
            get {
                return ResourceManager.GetString("Ivory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump in!.
        /// </summary>
        public static string JumpIn {
            get {
                return ResourceManager.GetString("JumpIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khaki.
        /// </summary>
        public static string Khaki {
            get {
                return ResourceManager.GetString("Khaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE LEARNING.
        /// </summary>
        public static string LanguageLearning {
            get {
                return ResourceManager.GetString("LanguageLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform your phone into a best language learning tool. Learn a new word from a language of your choice right from the lock screen!.
        /// </summary>
        public static string LanguageLearningText {
            get {
                return ResourceManager.GetString("LanguageLearningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to learn today?.
        /// </summary>
        public static string LanguageSetting {
            get {
                return ResourceManager.GetString("LanguageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavender.
        /// </summary>
        public static string Lavender {
            get {
                return ResourceManager.GetString("Lavender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavender Blush.
        /// </summary>
        public static string LavenderBlush {
            get {
                return ResourceManager.GetString("LavenderBlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawn Green.
        /// </summary>
        public static string LawnGreen {
            get {
                return ResourceManager.GetString("LawnGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lemon Chiffon.
        /// </summary>
        public static string LemonChiffon {
            get {
                return ResourceManager.GetString("LemonChiffon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s go!.
        /// </summary>
        public static string LetsGo {
            get {
                return ResourceManager.GetString("LetsGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Blue.
        /// </summary>
        public static string LightBlue {
            get {
                return ResourceManager.GetString("LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Coral.
        /// </summary>
        public static string LightCoral {
            get {
                return ResourceManager.GetString("LightCoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Cyan.
        /// </summary>
        public static string LightCyan {
            get {
                return ResourceManager.GetString("LightCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Goldenrod Yellow.
        /// </summary>
        public static string LightGoldenrodYellow {
            get {
                return ResourceManager.GetString("LightGoldenrodYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Gray.
        /// </summary>
        public static string LightGray {
            get {
                return ResourceManager.GetString("LightGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Green.
        /// </summary>
        public static string LightGreen {
            get {
                return ResourceManager.GetString("LightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Pink.
        /// </summary>
        public static string LightPink {
            get {
                return ResourceManager.GetString("LightPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Salmon.
        /// </summary>
        public static string LightSalmon {
            get {
                return ResourceManager.GetString("LightSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Sea Green.
        /// </summary>
        public static string LightSeaGreen {
            get {
                return ResourceManager.GetString("LightSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Sky Blue.
        /// </summary>
        public static string LightSkyBlue {
            get {
                return ResourceManager.GetString("LightSkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Slate Gray.
        /// </summary>
        public static string LightSlateGray {
            get {
                return ResourceManager.GetString("LightSlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Steel Blue.
        /// </summary>
        public static string LightSteelBlue {
            get {
                return ResourceManager.GetString("LightSteelBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Yellow.
        /// </summary>
        public static string LightYellow {
            get {
                return ResourceManager.GetString("LightYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime.
        /// </summary>
        public static string Lime {
            get {
                return ResourceManager.GetString("Lime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime Green.
        /// </summary>
        public static string LimeGreen {
            get {
                return ResourceManager.GetString("LimeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linen.
        /// </summary>
        public static string Linen {
            get {
                return ResourceManager.GetString("Linen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living.
        /// </summary>
        public static string Living {
            get {
                return ResourceManager.GetString("Living", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock screen.
        /// </summary>
        public static string lockscreen {
            get {
                return ResourceManager.GetString("lockscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        public static string Magenta {
            get {
                return ResourceManager.GetString("Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maroon.
        /// </summary>
        public static string Maroon {
            get {
                return ResourceManager.GetString("Maroon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Aquamarine.
        /// </summary>
        public static string MediumAquamarine {
            get {
                return ResourceManager.GetString("MediumAquamarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Blue.
        /// </summary>
        public static string MediumBlue {
            get {
                return ResourceManager.GetString("MediumBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Orchid.
        /// </summary>
        public static string MediumOrchid {
            get {
                return ResourceManager.GetString("MediumOrchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Purple.
        /// </summary>
        public static string MediumPurple {
            get {
                return ResourceManager.GetString("MediumPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Sea Green.
        /// </summary>
        public static string MediumSeaGreen {
            get {
                return ResourceManager.GetString("MediumSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Slate Blue.
        /// </summary>
        public static string MediumSlateBlue {
            get {
                return ResourceManager.GetString("MediumSlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Spring Green.
        /// </summary>
        public static string MediumSpringGreen {
            get {
                return ResourceManager.GetString("MediumSpringGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Turquoise.
        /// </summary>
        public static string MediumTurquoise {
            get {
                return ResourceManager.GetString("MediumTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Violet Red.
        /// </summary>
        public static string MediumVioletRed {
            get {
                return ResourceManager.GetString("MediumVioletRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midnight Blue.
        /// </summary>
        public static string MidnightBlue {
            get {
                return ResourceManager.GetString("MidnightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military.
        /// </summary>
        public static string Military {
            get {
                return ResourceManager.GetString("Military", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mint Cream.
        /// </summary>
        public static string MintCream {
            get {
                return ResourceManager.GetString("MintCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misty Rose.
        /// </summary>
        public static string MistyRose {
            get {
                return ResourceManager.GetString("MistyRose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moccasin.
        /// </summary>
        public static string Moccasin {
            get {
                return ResourceManager.GetString("Moccasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mundane.
        /// </summary>
        public static string mundane {
            get {
                return ResourceManager.GetString("mundane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASA.
        /// </summary>
        public static string NASA {
            get {
                return ResourceManager.GetString("NASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the explaination for the image shown on your screen. This option is only available if you&apos;re using NASA as your image provider in the previous screen..
        /// </summary>
        public static string NASAInterestText {
            get {
                return ResourceManager.GetString("NASAInterestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NASA IMAGE CAPTION.
        /// </summary>
        public static string NASAInterestTitle {
            get {
                return ResourceManager.GetString("NASAInterestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is more beautiful than the mother universe. NASA Images enlight your day from the beginning. If you choose this option, you agree that all rights belong to the respective owners of the image..
        /// </summary>
        public static string NASAText {
            get {
                return ResourceManager.GetString("NASAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navajo White.
        /// </summary>
        public static string NavajoWhite {
            get {
                return ResourceManager.GetString("NavajoWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navy.
        /// </summary>
        public static string Navy {
            get {
                return ResourceManager.GetString("Navy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Source.
        /// </summary>
        public static string NewsSource {
            get {
                return ResourceManager.GetString("NewsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! We have taken care of everything. If you haven&apos;t already, press Finalize and you&apos;re good to go. And oh, by the way, take a look at your Lock Screen..
        /// </summary>
        public static string NothingToDo {
            get {
                return ResourceManager.GetString("NothingToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come back later, as you still have sufficient balance. We&apos;ll remind you when it is running out..
        /// </summary>
        public static string NotThereYetText {
            get {
                return ResourceManager.GetString("NotThereYetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT THERE YET.
        /// </summary>
        public static string NotThereYetTitle {
            get {
                return ResourceManager.GetString("NotThereYetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO NOT UNINSTALL.
        /// </summary>
        public static string NoUninstallation {
            get {
                return ResourceManager.GetString("NoUninstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you uninstall, all your quota will be gone (you will still get the free quota)..
        /// </summary>
        public static string NoUninstallationText {
            get {
                return ResourceManager.GetString("NoUninstallationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Lace.
        /// </summary>
        public static string OldLace {
            get {
                return ResourceManager.GetString("OldLace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive.
        /// </summary>
        public static string Olive {
            get {
                return ResourceManager.GetString("Olive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive Drab.
        /// </summary>
        public static string OliveDrab {
            get {
                return ResourceManager.GetString("OliveDrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange Red.
        /// </summary>
        public static string OrangeRed {
            get {
                return ResourceManager.GetString("OrangeRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchid.
        /// </summary>
        public static string Orchid {
            get {
                return ResourceManager.GetString("Orchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Goldenrod.
        /// </summary>
        public static string PaleGoldenrod {
            get {
                return ResourceManager.GetString("PaleGoldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Green.
        /// </summary>
        public static string PaleGreen {
            get {
                return ResourceManager.GetString("PaleGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Turquoise.
        /// </summary>
        public static string PaleTurquoise {
            get {
                return ResourceManager.GetString("PaleTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Violet Red.
        /// </summary>
        public static string PaleVioletRed {
            get {
                return ResourceManager.GetString("PaleVioletRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papaya Whip.
        /// </summary>
        public static string PapayaWhip {
            get {
                return ResourceManager.GetString("PapayaWhip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peach Puff.
        /// </summary>
        public static string PeachPuff {
            get {
                return ResourceManager.GetString("PeachPuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        public static string Peru {
            get {
                return ResourceManager.GetString("Peru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin a shortcut to the story.
        /// </summary>
        public static string PinShortcut {
            get {
                return ResourceManager.GetString("PinShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin shortcut.
        /// </summary>
        public static string PinShortcutButton {
            get {
                return ResourceManager.GetString("PinShortcutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also pin a short cut tile on the start screen so you can jump to the story real quick..
        /// </summary>
        public static string PinShortcutDetails {
            get {
                return ResourceManager.GetString("PinShortcutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plum.
        /// </summary>
        public static string Plum {
            get {
                return ResourceManager.GetString("Plum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politics.
        /// </summary>
        public static string Politics {
            get {
                return ResourceManager.GetString("Politics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powder Blue.
        /// </summary>
        public static string PowderBlue {
            get {
                return ResourceManager.GetString("PowderBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can customize styles by tapping the preview texts..
        /// </summary>
        public static string PreviewPageIntro {
            get {
                return ResourceManager.GetString("PreviewPageIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is my price calculated?.
        /// </summary>
        public static string PriceCalc {
            get {
                return ResourceManager.GetString("PriceCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase .
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redeem.
        /// </summary>
        public static string Redeem {
            get {
                return ResourceManager.GetString("Redeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REDEEM A CODE.
        /// </summary>
        public static string RedeemACode {
            get {
                return ResourceManager.GetString("RedeemACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your code below. It should look something like this: XXXXX-XXXXX-XXXXX-XXXXX-XXXXX.
        /// </summary>
        public static string RedeemACodeGuide {
            get {
                return ResourceManager.GetString("RedeemACodeGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but this doesn&apos;t look like a valid code..
        /// </summary>
        public static string RedeemStatusNotOkay {
            get {
                return ResourceManager.GetString("RedeemStatusNotOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! You can now enjoy LockView free of charge..
        /// </summary>
        public static string RedeemStatusOkay {
            get {
                return ResourceManager.GetString("RedeemStatusOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your remaining balance lasts:.
        /// </summary>
        public static string RemainingBalance {
            get {
                return ResourceManager.GetString("RemainingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockView uses a web service to compose your image. LockView maintains this service by kindly ask you to purchase your quota for $.
        /// </summary>
        public static string RemainingBalanceText {
            get {
                return ResourceManager.GetString("RemainingBalanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosy Brown.
        /// </summary>
        public static string RosyBrown {
            get {
                return ResourceManager.GetString("RosyBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royal Blue.
        /// </summary>
        public static string RoyalBlue {
            get {
                return ResourceManager.GetString("RoyalBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saddle Brown.
        /// </summary>
        public static string SaddleBrown {
            get {
                return ResourceManager.GetString("SaddleBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salmon.
        /// </summary>
        public static string Salmon {
            get {
                return ResourceManager.GetString("Salmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandy Brown.
        /// </summary>
        public static string SandyBrown {
            get {
                return ResourceManager.GetString("SandyBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to say yes.
        /// </summary>
        public static string SayYes {
            get {
                return ResourceManager.GetString("SayYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Green.
        /// </summary>
        public static string SeaGreen {
            get {
                return ResourceManager.GetString("SeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Shell.
        /// </summary>
        public static string SeaShell {
            get {
                return ResourceManager.GetString("SeaShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence.
        /// </summary>
        public static string Sentence {
            get {
                return ResourceManager.GetString("Sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as lock screen provider and allow background update.
        /// </summary>
        public static string SetAsLockScreen {
            get {
                return ResourceManager.GetString("SetAsLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Me!.
        /// </summary>
        public static string ShowMe {
            get {
                return ResourceManager.GetString("ShowMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sienna.
        /// </summary>
        public static string Sienna {
            get {
                return ResourceManager.GetString("Sienna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size per request:.
        /// </summary>
        public static string SizePerRequest {
            get {
                return ResourceManager.GetString("SizePerRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is based on the size of the cropped image you just selected, plus some metadata. This may vary a bit if you use automatic image update..
        /// </summary>
        public static string SizePerRequestExplained {
            get {
                return ResourceManager.GetString("SizePerRequestExplained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky Blue.
        /// </summary>
        public static string SkyBlue {
            get {
                return ResourceManager.GetString("SkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slate Blue.
        /// </summary>
        public static string SlateBlue {
            get {
                return ResourceManager.GetString("SlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slate Gray.
        /// </summary>
        public static string SlateGray {
            get {
                return ResourceManager.GetString("SlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string Snow {
            get {
                return ResourceManager.GetString("Snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Society.
        /// </summary>
        public static string Society {
            get {
                return ResourceManager.GetString("Society", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIFIC TOPIC OF YOUR CHOICE.
        /// </summary>
        public static string SpecificTopicOfYourChoice {
            get {
                return ResourceManager.GetString("SpecificTopicOfYourChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows user to use a specific topic of their interest..
        /// </summary>
        public static string SpecificTopicOfYourChoiceText {
            get {
                return ResourceManager.GetString("SpecificTopicOfYourChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockView is not a news provider. All related news is culled from Internet..
        /// </summary>
        public static string SpecificTopicPageDisclaimer {
            get {
                return ResourceManager.GetString("SpecificTopicPageDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in a specific topic. e.g. Apple, UW, Google, President, Seahawk..
        /// </summary>
        public static string SpecificTopicPageText {
            get {
                return ResourceManager.GetString("SpecificTopicPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about a specific topic. We&apos;ll gather all news about it for you..
        /// </summary>
        public static string SpecificTopicPageTitle {
            get {
                return ResourceManager.GetString("SpecificTopicPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        public static string Sports {
            get {
                return ResourceManager.GetString("Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring Green.
        /// </summary>
        public static string SpringGreen {
            get {
                return ResourceManager.GetString("SpringGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Blue.
        /// </summary>
        public static string SteelBlue {
            get {
                return ResourceManager.GetString("SteelBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which .
        /// </summary>
        public static string StockQuoteTitle {
            get {
                return ResourceManager.GetString("StockQuoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stories.
        /// </summary>
        public static string Stories {
            get {
                return ResourceManager.GetString("Stories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Source.
        /// </summary>
        public static string SuggestedSource {
            get {
                return ResourceManager.GetString("SuggestedSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan.
        /// </summary>
        public static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        public static string Teal {
            get {
                return ResourceManager.GetString("Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string Technology {
            get {
                return ResourceManager.GetString("Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s it!.
        /// </summary>
        public static string ThatsIt {
            get {
                return ResourceManager.GetString("ThatsIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thistle.
        /// </summary>
        public static string Thistle {
            get {
                return ResourceManager.GetString("Thistle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Background.
        /// </summary>
        public static string TitleBackground {
            get {
                return ResourceManager.GetString("TitleBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Font Size.
        /// </summary>
        public static string TitleFontSize {
            get {
                return ResourceManager.GetString("TitleFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Foreground.
        /// </summary>
        public static string TitleForeground {
            get {
                return ResourceManager.GetString("TitleForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomato.
        /// </summary>
        public static string Tomato {
            get {
                return ResourceManager.GetString("Tomato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Price:.
        /// </summary>
        public static string TrafficPrice {
            get {
                return ResourceManager.GetString("TrafficPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is what our service provider charges us for network traffic. If our service provider lowers their traffic price, we&apos;ll lower ours too!.
        /// </summary>
        public static string TrafficPriceExplained {
            get {
                return ResourceManager.GetString("TrafficPriceExplained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Language.
        /// </summary>
        public static string TranslationLanguage {
            get {
                return ResourceManager.GetString("TranslationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        public static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel.
        /// </summary>
        public static string Travel {
            get {
                return ResourceManager.GetString("Travel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquoise.
        /// </summary>
        public static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METRIC.
        /// </summary>
        public static string UnitMetric {
            get {
                return ResourceManager.GetString("UnitMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use imperial.
        /// </summary>
        public static string UseImperial {
            get {
                return ResourceManager.GetString("UseImperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use metric.
        /// </summary>
        public static string UseMetric {
            get {
                return ResourceManager.GetString("UseMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use my location.
        /// </summary>
        public static string UseMyLocation {
            get {
                return ResourceManager.GetString("UseMyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE MY OWN IMAGE.
        /// </summary>
        public static string UseOwnImage {
            get {
                return ResourceManager.GetString("UseOwnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this if you would like to use the same image as your lock screen over time. In the next step we will let you pick one from your library..
        /// </summary>
        public static string UseOwnImageText {
            get {
                return ResourceManager.GetString("UseOwnImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        public static string Violet {
            get {
                return ResourceManager.GetString("Violet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEATHER.
        /// </summary>
        public static string WeatherInterest {
            get {
                return ResourceManager.GetString("WeatherInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always worried about rain? Track your favourite city&apos;s immediate weather condition right on your Lock Screen..
        /// </summary>
        public static string WeatherInterestText {
            get {
                return ResourceManager.GetString("WeatherInterestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just put in the name of the city. We&apos;ll give you its immediate weather forcast so you won&apos;t be caught by bad weather!.
        /// </summary>
        public static string WeatherSettingPageText {
            get {
                return ResourceManager.GetString("WeatherSettingPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you want to track?.
        /// </summary>
        public static string WeatherSettingPageTitle {
            get {
                return ResourceManager.GetString("WeatherSettingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheat.
        /// </summary>
        public static string Wheat {
            get {
                return ResourceManager.GetString("Wheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While your balance lasts, you receive full feature of the application. As an encouragement to support our work, you will have to reinstall this app to get some new balance every few days..
        /// </summary>
        public static string WhileBalanceLastsText {
            get {
                return ResourceManager.GetString("WhileBalanceLastsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;M NOT A FAN OF PAID APP....
        /// </summary>
        public static string WhileBalanceLastsTitle {
            get {
                return ResourceManager.GetString("WhileBalanceLastsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Smoke.
        /// </summary>
        public static string WhiteSmoke {
            get {
                return ResourceManager.GetString("WhiteSmoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORD OF WISDOM.
        /// </summary>
        public static string WordOfWisdom {
            get {
                return ResourceManager.GetString("WordOfWisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in something here. It will show up on your screen..
        /// </summary>
        public static string WordOfWisdomPageGuide {
            get {
                return ResourceManager.GetString("WordOfWisdomPageGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there anything you want to tell yourself? Maybe to calm down, slow down?.
        /// </summary>
        public static string WordOfWisdomPageIntro {
            get {
                return ResourceManager.GetString("WordOfWisdomPageIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in something here. It will show up on your screen..
        /// </summary>
        public static string WordOfWisdomPageText {
            get {
                return ResourceManager.GetString("WordOfWisdomPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there anything you want to tell yourself? Maybe to calm down, slow down?.
        /// </summary>
        public static string WordOfWisdomPageTitle {
            get {
                return ResourceManager.GetString("WordOfWisdomPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank, or use a sentence that you&apos;ve been telling yourself..
        /// </summary>
        public static string WordOfWisdomText {
            get {
                return ResourceManager.GetString("WordOfWisdomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Phone requires us to obtain your consent before we can change your lock screen..
        /// </summary>
        public static string WPRestrictions {
            get {
                return ResourceManager.GetString("WPRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Green.
        /// </summary>
        public static string YellowGreen {
            get {
                return ResourceManager.GetString("YellowGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string ZhCn {
            get {
                return ResourceManager.GetString("ZhCn", resourceCulture);
            }
        }
    }
}
